// Generated by Skyramp v1.3.22 on 2026-05-01 22:08:03.1275166 +0000 UTC m=+298.664456835
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ping_health_check_integration_test.spec.ts \
// 		--output-dir /home/runner/work/medusa/medusa/tests/skyramp/api \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/medusa/medusa/tests/skyramp/api/scenario_ping-health-check.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Execute Request
    let pingGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/ping",
        method:"GET"
    });

    // Generated Assertions
    expect(pingGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(pingGetResponse, "ok"), 'ok value').toBe(true);
});

