// Generated by Skyramp v1.3.22 on 2026-05-01 22:07:52.206460749 +0000 UTC m=+287.743400974
// Command: skyramp generate contract rest http://localhost:9000/ping \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output ping_contract_no_auth.spec.ts \
// 		--output-dir /home/runner/work/medusa/medusa/tests/skyramp/api \
// 		--overwrite \
// 		--provider \
// 		--response-data {"ok":true} \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9000");

// contract test for /ping GET
test('testPingGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedPingGetResponseBody: string = `{
        "ok": true
    }`;

    // Execute Request
    const pingGetResponse = await client.sendRequest({
        url: URL,
        path: "/ping",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(pingGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(pingGetResponse, expectedPingGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(pingGetResponse, "ok"), 'value').toBe(true);
});
